
INSERT INTO HOTEL (  HOTEL_ID, HOTEL_NAME, HOTEL_RATINGS ) VALUES
(101, 'Air Asia Holiday Inn Kuala lumpur', 5 );

INSERT INTO HOTEL (  HOTEL_ID, HOTEL_NAME, HOTEL_RATINGS ) VALUES
(102, 'Air Asia Hotel and Residence Inn Kuala lumpur', 5 );

INSERT INTO HOTEL (  HOTEL_ID, HOTEL_NAME, HOTEL_RATINGS ) VALUES
(103, 'Air Asia villas Kuala lumpur', 5 );

INSERT INTO HOTEL (  HOTEL_ID, HOTEL_NAME, HOTEL_RATINGS ) VALUES
(104, 'Air Asia suites Kuala lumpur', 5 );

INSERT INTO ROOM (HOTEL_ID,ROOM_ID,ROOM_NAME,TOTAL_ROOMS,ADULT_CAPACITY,CHILD_CAPACITY,NON_SMOKING,FREE_WIFI,RATINGS,PRICE )
VALUES(
101,101, 'Single Room', 15, 1, 1, 'Y', 'Y', 5 , 150 );

INSERT INTO ROOM (HOTEL_ID,ROOM_ID,ROOM_NAME,TOTAL_ROOMS,ADULT_CAPACITY,CHILD_CAPACITY,NON_SMOKING,FREE_WIFI,RATINGS,PRICE )
VALUES(
101,102, 'Twin Room', 10, 2, 2, 'Y', 'Y', 5 , 180 );

INSERT INTO ROOM (HOTEL_ID,ROOM_ID,ROOM_NAME,TOTAL_ROOMS,ADULT_CAPACITY,CHILD_CAPACITY,NON_SMOKING,FREE_WIFI,RATINGS,PRICE )
VALUES(
101,103, 'Double Room with King Bed', 10, 2, 2, 'Y', 'Y', 5 , 200 );

INSERT INTO ROOM (HOTEL_ID,ROOM_ID,ROOM_NAME,TOTAL_ROOMS,ADULT_CAPACITY,CHILD_CAPACITY,NON_SMOKING,FREE_WIFI,RATINGS,PRICE )
VALUES(
101,104, 'Double Room with King Bed', 10, 2, 2, 'Y', 'Y', 5 , 250 );

INSERT INTO ROOM (HOTEL_ID,ROOM_ID,ROOM_NAME,TOTAL_ROOMS,ADULT_CAPACITY,CHILD_CAPACITY,NON_SMOKING,FREE_WIFI,RATINGS,PRICE )
VALUES(
101,105, 'Standard Quadruple Room', 5, 4, 2, 'Y', 'Y', 5 , 330 );

INSERT INTO ROOM (HOTEL_ID,ROOM_ID,ROOM_NAME,TOTAL_ROOMS,ADULT_CAPACITY,CHILD_CAPACITY,NON_SMOKING,FREE_WIFI,RATINGS,PRICE )
VALUES(
101,106, 'Superior Quadruple Room', 5, 5, 2, 'Y', 'Y', 5 , 520 );


INSERT INTO ROOM (HOTEL_ID,ROOM_ID,ROOM_NAME,TOTAL_ROOMS,ADULT_CAPACITY,CHILD_CAPACITY,NON_SMOKING,FREE_WIFI,RATINGS,PRICE )
VALUES(
102,101, 'Single Room', 20, 1, 1, 'Y', 'Y', 5 , 100 );

INSERT INTO ROOM (HOTEL_ID,ROOM_ID,ROOM_NAME,TOTAL_ROOMS,ADULT_CAPACITY,CHILD_CAPACITY,NON_SMOKING,FREE_WIFI,RATINGS,PRICE )
VALUES(
102,102, 'Twin Room', 20, 2, 2, 'Y', 'Y', 5 , 150 );

INSERT INTO ROOM (HOTEL_ID,ROOM_ID,ROOM_NAME,TOTAL_ROOMS,ADULT_CAPACITY,CHILD_CAPACITY,NON_SMOKING,FREE_WIFI,RATINGS,PRICE )
VALUES(
102,103, 'Double Room with King Bed', 10, 2, 2, 'Y', 'Y', 5 , 200 );

INSERT INTO ROOM (HOTEL_ID,ROOM_ID,ROOM_NAME,TOTAL_ROOMS,ADULT_CAPACITY,CHILD_CAPACITY,NON_SMOKING,FREE_WIFI,RATINGS,PRICE )
VALUES(
102,104, 'Double Room with King Bed', 10, 2, 2, 'Y', 'Y', 5 , 250 );



INSERT INTO ROOM (HOTEL_ID,ROOM_ID,ROOM_NAME,TOTAL_ROOMS,ADULT_CAPACITY,CHILD_CAPACITY,NON_SMOKING,FREE_WIFI,RATINGS,PRICE )
VALUES(
103,101, 'Double Room with King Bed', 20, 2, 2, 'Y', 'Y', 5 , 340 );

INSERT INTO ROOM (HOTEL_ID,ROOM_ID,ROOM_NAME,TOTAL_ROOMS,ADULT_CAPACITY,CHILD_CAPACITY,NON_SMOKING,FREE_WIFI,RATINGS,PRICE )
VALUES(
103,102, 'Double Room with King Bed', 20, 2, 2, 'Y', 'Y', 5 , 410 );

INSERT INTO ROOM (HOTEL_ID,ROOM_ID,ROOM_NAME,TOTAL_ROOMS,ADULT_CAPACITY,CHILD_CAPACITY,NON_SMOKING,FREE_WIFI,RATINGS,PRICE )
VALUES(
103,103, 'Standard Quadruple Room', 15, 4, 2, 'Y', 'Y', 5 , 670 );

INSERT INTO ROOM (HOTEL_ID,ROOM_ID,ROOM_NAME,TOTAL_ROOMS,ADULT_CAPACITY,CHILD_CAPACITY,NON_SMOKING,FREE_WIFI,RATINGS,PRICE )
VALUES(
103,104, 'Superior Quadruple Room', 15, 5, 2, 'Y', 'Y', 5 , 800 );


INSERT INTO ROOM (HOTEL_ID,ROOM_ID,ROOM_NAME,TOTAL_ROOMS,ADULT_CAPACITY,CHILD_CAPACITY,NON_SMOKING,FREE_WIFI,RATINGS,PRICE )
VALUES(
104,101, 'Single Room', 15, 1, 1, 'Y', 'Y', 5 , 150 );

INSERT INTO ROOM (HOTEL_ID,ROOM_ID,ROOM_NAME,TOTAL_ROOMS,ADULT_CAPACITY,CHILD_CAPACITY,NON_SMOKING,FREE_WIFI,RATINGS,PRICE )
VALUES(
104,102, 'Twin Room', 10, 2, 2, 'Y', 'Y', 5 , 180 );

INSERT INTO ROOM (HOTEL_ID,ROOM_ID,ROOM_NAME,TOTAL_ROOMS,ADULT_CAPACITY,CHILD_CAPACITY,NON_SMOKING,FREE_WIFI,RATINGS,PRICE )
VALUES(
104,103, 'Double Room with King Bed', 10, 2, 2, 'Y', 'Y', 5 , 200 );

INSERT INTO ROOM (HOTEL_ID,ROOM_ID,ROOM_NAME,TOTAL_ROOMS,ADULT_CAPACITY,CHILD_CAPACITY,NON_SMOKING,FREE_WIFI,RATINGS,PRICE )
VALUES(
104,104, 'Double Room with King Bed', 10, 2, 2, 'Y', 'Y', 5 , 250 );

INSERT INTO ROOM (HOTEL_ID,ROOM_ID,ROOM_NAME,TOTAL_ROOMS,ADULT_CAPACITY,CHILD_CAPACITY,NON_SMOKING,FREE_WIFI,RATINGS,PRICE )
VALUES(
104,105, 'Standard Quadruple Room', 5, 4, 2, 'Y', 'Y', 5 , 330 );

INSERT INTO ROOM (HOTEL_ID,ROOM_ID,ROOM_NAME,TOTAL_ROOMS,ADULT_CAPACITY,CHILD_CAPACITY,NON_SMOKING,FREE_WIFI,RATINGS,PRICE )
VALUES(
104,106, 'Superior Quadruple Room', 5, 5, 2, 'Y', 'Y', 5 , 520 );