CREATE TABLE ORDERS (
   ORDER_ID BIGINT NOT NULL, 
   ORDER_STATUS VARCHAR(50) NOT NULL, 
   ORDER_DATE DATE NOT NULL, 
   HOTEL_ID BIGINT NOT NULL,
   GUEST_ID BIGINT NOT NULL,
   CHECK_IN_DATE DATE NOT NULL,
   CHECK_OUT_DATE  DATE NOT NULL,
   ORDER_PRICE DECIMAL NOT NULL
   );
   
ALTER TABLE ORDERS ADD PRIMARY KEY (ORDER_ID);

CREATE TABLE ORDER_DETAILS (
   ORDER_ID BIGINT NOT NULL, 
   HOTEL_ID BIGINT NOT NULL,
   ROOM_ID BIGINT NOT NULL,
   ROOM_COUNT INT NOT NULL 
   );
   
ALTER TABLE ORDER_DETAILS ADD PRIMARY KEY (ORDER_ID, ROOM_ID);

CREATE TABLE HOTEL (
   HOTEL_ID BIGINT NOT NULL, 
   HOTEL_NAME VARCHAR(2000) NOT NULL, 
   HOTEL_RATINGS INT 
   );
ALTER TABLE HOTEL ADD PRIMARY KEY (HOTEL_ID);

CREATE TABLE GUEST (
   TITLE VARCHAR(3) NOT NULL, 
   GUEST_ID BIGINT NOT NULL, 
   FIRST_NAME VARCHAR(100) NOT NULL, 
   LAST_NAME VARCHAR(100) ,
   CONTACT_NUM VARCHAR(20) ,
   EMAIL_ID VARCHAR(500)
   );

ALTER TABLE GUEST ADD PRIMARY KEY (GUEST_ID);


CREATE TABLE ROOM (
   HOTEL_ID BIGINT NOT NULL, 
   ROOM_ID BIGINT NOT NULL,
   ROOM_NAME VARCHAR(500) NOT NULL,
   TOTAL_ROOMS INT NOT NULL,
   ADULT_CAPACITY INT NOT NULL,
   CHILD_CAPACITY INT NOT NULL,
   NON_SMOKING CHAR(1) ,
   FREE_WIFI CHAR(1) ,
   RATINGS INT,
   PRICE DECIMAL NOT NULL
   );

ALTER TABLE ROOM ADD PRIMARY KEY (HOTEL_ID, ROOM_ID);

